@startuml

' Define instances of Folder and File after the 'app' folder deletion

object Folder {
  name = "php_demo1"
}

object SubFolder1 {
  name = "Source Files"
}

object SubFolder1_1 {
  name = ".phalcon"
}

object SubFolder1_3 {
  name = "cache"
}

object SubFolder1_4 {
  name = "public"
}

object File1_4_1 {
  name = ".htaccess"
}

object File1_4_2 {
  name = ".htrouter.php"
}

object File1_4_3 {
  name = "index.html"
}

object SubFolder2 {
  name = "Include Path"
}

object SubFolder3 {
  name = "Remote Files"
}

' Define the links representing the composition relationships
Folder -right-> SubFolder1 : subfolders
SubFolder1 -down-> SubFolder1_1 : subfolders
SubFolder1 -down-> SubFolder1_3 : subfolders
SubFolder1 -down-> SubFolder1_4 : subfolders
SubFolder1_4 -right-> File1_4_1 : files
SubFolder1_4 -right-> File1_4_2 : files
SubFolder1_4 -right-> File1_4_3 : files
Folder -right-> SubFolder2 : subfolders
Folder -right-> SubFolder3 : subfolders

@enduml
